routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/mentionslegales', function () {
    return view('components/mentionslegales');
});

Route::get('/index_anglais', function () {
    return view('index_anglais');
});
Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('menus', 'MenuController');

Route::resource('menus', 'MenuInfoController');

Route::resource('menu_entree', 'MenuEntreeController');

Route::resource('menu_plat', 'MenuPlatController');

Route::resource('menu_dessert', 'MenuDessertController');

Route::resource('plats', 'PlatController');

Route::resource('Formule_Express', 'Formule_ExpressController');

Route::resource('entrees','EntreesController');

Route::resource('plats', 'PlatController');

app/Plat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plat extends Model
{
     protected $fillable = [
    'nom',
    'nom_anglais',
    'description',
    'description_anglais',
    'fait_maison',
    'prix'
  ];
}

app/Http/Controllers/PlatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Plat;

class PlatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plats=Plat::All();
        return view('plats.index', compact('plats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('plats.create');
   }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nom'=>'required|string',
            'nom_anglais'=> 'required|string',
            'description' => 'required|string',
            'description_anglais'=>'required|string',
            'prix'=>'required|string',
            'fait_maison'=>''
        ]);
        $plat = new Plat([
            'nom' => $request->get('nom'),
            'nom_anglais'=> $request->get('nom_anglais'),
            'description'=> $request->get('description'),
            'description_anglais'=>$request->get('description_anglais'),
            'prix'=>$request->get('prix'),
            'fait_maison'=>$request->get('fait_maison')
        ]);
        $plat->save();
        return redirect('/plats')->with('success', 'Le plat a été ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $plat = Plat::find($id);

        return view('plats.edit', compact('plat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nom'=>'required|string',
            'nom_anglais'=> 'required|string',
            'description' => 'required|string',
            'description_anglais'=>'required|string',
            'prix'=>'required|string',
            'fait_maison'=>''
        ]);
        $plat = Plat::find($id);
        $plat->nom = $request->get('nom');
        $plat->nom_anglais = $request->get('nom_anglais');
        $plat->description = $request->get('description');
        $plat->description_anglais = $request->get('description_anglais');
        $plat->prix = $request->get('prix');
        $plat->fait_maison = $request->get('fait_maison');
        $plat->save();
        return redirect('/plats')->with('success', 'Le plat a été modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    $plat = Plat::find($id);
    $plat->delete();

     return redirect('/plats')->with("success", "le plat a bien été suprimé");
    }
}

resources/views/plats/create.blade.php
@extends('layouts.app')
@section('content')

<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('plats.store') }}">
          <div class="form-group">
              @csrf
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom"/>
          </div>
          <div class="form-group">
              <label for="nom_anglais">Nom Anglais :</label>
              <input type="text" class="form-control" name="nom_anglais"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>
          <div class="form-group">
              <label for="description_anglais">Description Anglais :</label>
              <input type="text" class="form-control" name="description_anglais"/>
          </div>
          
          <div class="form-group">
            <label for="select">Fait maison</label>
            <input type="checkbox" value="1" checked id="fait_maison" name="fait_maison">
        </div>

          <div class="form-group">
              <label for="prix">Prix :</label>
              <input type="text" class="form-control" name="prix"/>
          </div>
          <button type="submit" class="btn btn-success">Valider</button>
      </form>
  </div>
</div>

@endsection

resources/views/plats/delete.blade.php
@extends('layouts.app')
@section('content')
@endsection

resources/views/plats/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container create-menu">
    <h1 class="text-center">MODIFIER UN ÉLÉMENT DU MENU</h1>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <form action="{{ route('plats.update', $plat->id) }}" method="post">
        @method('PATCH')
        @csrf
        <div class="form-group">
            <label for="nom">Nom</label>
            <input type="text" id="nom" name="nom" class="form-control" placeholder="Entrez un élément de menu" value="{{$plat->nom}}">
        </div>

        <div class="form-group">
            <label for="nom_anglais">Nom (traduction anglaise)</label>
            <input type="text" id="nom_anglais" name="nom_anglais" class="form-control" placeholder="Entrez un élément de menu en anglais" value="{{$plat->nom_anglais}}">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" id="description" name="description" class="form-control" placeholder="Entrez une description" value="{{$plat->description}}">
        </div>


        <div class="form-group">
            <label for="description_anglais">Description (traduction anglaise)</label>
            <input type="text" id="description_anglais" name="description_anglais" class="form-control" placeholder="Entrez une description en anglais" value="{{$plat->description_anglais}}">
        </div>

        <div class="form-group">
            <label for="select">Fait maison</label>
            <input type="checkbox" value="1" checked id="fait_maison" name="fait_maison">
        </div>
        
        <div class="form-group">
            <label for="prix">Prix</label>
            <input type="text" id="prix" name="prix" class="form-control" placeholder="Entrez un prix" value="{{$plat->prix}}">
        </div>

        <button type="submit" class="btn btn-success">Valider</button>
    </form>
</div>
@endsection

resources/views/plats/index.blade.php
@extends('layouts.app')

@section('content')

@if(session()->get('success'))
<div class="alert alert-success">
  {{ session()->get('success') }}  
</div><br />
@endif
<div class="card-columns">
    @foreach($plats as $plat)
    <div class="card">
        <div class="card-header">
            <div class="card-title">Élément de menu</div>
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><p class="text-center">{{$plat->nom}}<br>- <br>{{$plat->nom_anglais}}</p></li>
            </ul>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><i><p class="text-center">{{$plat->description}} <br> - <br> {{$plat->description_anglais}} </p></i></li>
                @if($plat->fait_maison == 1)
                <li class="list-group-item crud"><img src="https://monkeychamonix.com/site/wp-content/uploads/2014/08/icon_60175.png" width="50" height="50" alt=""></li>
                @endif            
            </ul>
             <ul class="list-group list-group-flush">
                <li class="list-group-item"><i><p class="text-center">{{$plat->prix}}</p></li>
            </ul>
            <ul class="list-group list-group-flush">
                <li class="list-group-item crud"><a href="{{ route('plats.edit',$plat->id)}}" class="btn btn-primary">Modifier</a>
                    
                    <form action="{{ route('plats.destroy', $plat->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                         <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                              Supprimer
                                            </button>
                                          </form>    

                </li>
            </ul>
        </div>
    </div>
    @endforeach
    <a class="nav-link" href="{{ route('plats.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>
</div>


@endsection