routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/mentionslegales', function () {
    return view('components/mentionslegales');
});

Route::get('/index_anglais', function () {
    return view('index_anglais');
});
Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('menus', 'MenuController');

Route::resource('menus', 'MenuInfoController');

Route::resource('menu_entree', 'MenuEntreeController');

Route::resource('menu_plat', 'MenuPlatController');

Route::resource('menu_dessert', 'MenuDessertController');

Route::resource('plats', 'PlatController');

Route::resource('Formule_Express', 'Formule_ExpressController');

Route::resource('entrees','EntreesController');

Route::resource('plats', 'PlatController');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $fillable = [
        'titre',
        'prix'
      ];
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;
use App\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::all();

        return view('menus.index', compact('menus'));
        return view('menu', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('menus.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           
            'titre'=>'',
            'prix'=>''
          ]);
          $menu = new Menu([
            'titre' => $request->get('titre'),
            'prix' => $request->get('prix')
          ]);
          $menu->save();
          return redirect('/menus')->with('success', "L'élément du menu à bien été ajouté");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menu = Menu::find($id);

        return view('menus.edit', compact('menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'titre'=>'required',
            'prix'=>''
          ]);
    
          $menu = Menu::find($id);
          $menu->titre = $request->get('titre');
          $menu->prix = $request->get('prix');
          $menu->save();
    
          return redirect('/menus')->with('success', "L'élément du menu à bien été mis à jour");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    $menu = Menu::find($id);
    $menu->delete();

    return redirect('/menus')->with("success", "l'élément a bien été suprimé");
    }
}

resources/views/menus/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container create-menu">
    <h1 class="text-center">CRÉER UN ÉLÉMENT DU MENU</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
        <form action="{{ route('menus.store') }}" method="post">
           
                    @csrf
                
                    <div class="form-group">
                        <label for="nom">Titre</label>
                    <input type="text" id="titre" name="titre" class="form-control" placeholder="Entrez un titre de menu">
                    </div>
        
                    <div class="form-group">
                        <label for="nom_anglais">Prix</label>
                        <input type="text" id="prix" name="prix" class="form-control" placeholder="Entrez un prix de menu" >
                    </div>
            
            <button type="submit" class="btn btn-success">Valider</button>
        </form>
</div>
@endsection

resources/views/menus/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container create-menu">
    <h1 class="text-center">MODIFIER UN ÉLÉMENT DU MENU</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
        <form action="{{ route('menus.update', $menu_info->id) }}" method="post">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="nom">Titre</label>
            <input type="text" id="titre" name="titre" class="form-control" placeholder="Entrez un titre de menu" value="{{$menu_info->titre}}">
            </div>

            <div class="form-group">
                <label for="nom_anglais">Prix</label>
                <input type="text" id="prix" name="prix" class="form-control" placeholder="Entrez un prix de menu" value="{{$menu_info->prix}}">
            </div>
            
            <button type="submit" class="btn btn-success">Valider</button>
        </form>
</div>
@endsection

resources/views/menus/index.blade.php
@extends('layouts.app')

@section('content')


  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
<div class="card-columns">


<div class="card">
  <div class="card-header">
    <div class="card-title">
      <p>Infos du menu</p>
    </div>
  </div>
    @foreach(App\MenuInfo::All() as $menu_info)
    <li class="list-group-item crud"><p>{{$menu_info->titre}}</p></li>
    <li class="list-group-item crud"><p>{{$menu_info->prix}}</p></li>
    <li class="list-group-item crud"><a href="{{ route('menus.edit',$menu_info->id)}}" class="btn btn-primary">Modifier</a>
      <form action="{{ route('menus.destroy', $menu_info->id)}}" method="post">
        @csrf
        @method('DELETE')
         <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#platModal">
          Supprimer
        </button>
      </form>
  @endforeach
  <a class="nav-link" href="{{ route('menus.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>

</div>

<div class="card">
  <div class="card-header">
    <div class="card-title"><p>Entrées du menu</p></div>
  </div>
    <div class="card-body">
        @foreach(App\MenuEntree::All() as $menu_entree)
        <li class="list-group-item crud"><p>{{$menu_entree->nom}}</p></li>
        <li class="list-group-item crud"><p>{{$menu_entree->description}}</p></li>
        @if($menu_entree->fait_maison == 1)
        <li class="list-group-item crud"><img src="https://monkeychamonix.com/site/wp-content/uploads/2014/08/icon_60175.png" width="50" height="50" alt=""></li>
        @endif
        <li class="list-group-item crud"><a href="{{ route('menu_entree.edit',$menu_entree->id)}}" class="btn btn-primary">Modifier</a>
          <form action="{{ route('menu_entree.destroy', $menu_entree->id)}}" method="post">
              @csrf
              @method('DELETE')
               <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#entreeModal">
                Supprimer
              </button>
            </form>
        @endforeach
    </div>
    <a class="nav-link" href="{{ route('menu_entree.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>

  
</div>



<div class="card">
    <div class="card-header">
      <div class="card-title"><p>Plats du menu</p></div>
    </div>
      <div class="card-body">
          @foreach(App\MenuPlat::All() as $menu_plat)
          <li class="list-group-item crud"><p>{{$menu_plat->nom}}</p></li>
          <li class="list-group-item crud"><p>{{$menu_plat->description}}</p></li>
          @if($menu_plat->fait_maison == 1)
          <li class="list-group-item crud"><img src="https://monkeychamonix.com/site/wp-content/uploads/2014/08/icon_60175.png" width="50" height="50" alt=""></li>
          @endif
          <li class="list-group-item crud"><a href="{{ route('menu_plat.edit',$menu_plat->id)}}" class="btn btn-primary">Modifier</a>
            <form action="{{ route('menu_plat.destroy', $menu_plat->id)}}" method="post">
                @csrf
                @method('DELETE')
                 <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#platModal">
                  Supprimer
                </button>
              </form>
          @endforeach
          
      </div>
      <a class="nav-link" href="{{ route('menu_plat.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>
  
  </div>


  <div class="card">
      <div class="card-header">
        <div class="card-title"><p>Fromages/Desserts du menu</p></div>
      </div>
        <div class="card-body">
            @foreach(App\menuDessert::All() as $menu_dessert)
            <li class="list-group-item crud"><p>{{$menu_dessert->nom}}</p></li>
            <li class="list-group-item crud"><p>{{$menu_dessert->description}}</p></li>
            @if($menu_dessert->fait_maison == 1)
            <li class="list-group-item crud"><img src="https://monkeychamonix.com/site/wp-content/uploads/2014/08/icon_60175.png" width="50" height="50" alt=""></li>
            @endif
            <li class="list-group-item crud"><a href="{{ route('menu_dessert.edit',$menu_dessert->id)}}" class="btn btn-primary">Modifier</a>
              <form action="{{ route('menu_dessert.destroy', $menu_dessert->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                   <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#dessertModal">
                    Supprimer
                  </button>
                </form>
              
              
            @endforeach
          </div>
            <a class="nav-link" href="{{ route('menu_dessert.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>
        
    
      </div>
    </div>
    
</div>
@endsection