routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/mentionslegales', function () {
    return view('components/mentionslegales');
});

Route::get('/index_anglais', function () {
    return view('index_anglais');
});
Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('menus', 'MenuController');

Route::resource('menus', 'MenuInfoController');

Route::resource('menu_entree', 'MenuEntreeController');

Route::resource('menu_plat', 'MenuPlatController');

Route::resource('menu_dessert', 'MenuDessertController');

Route::resource('plats', 'PlatController');

Route::resource('Formule_Express', 'Formule_ExpressController');

Route::resource('entrees','EntreesController');

Route::resource('plats', 'PlatController');

app/Http/Controllers/Formule_ExpressController.php
<?php

namespace App\Http\Controllers;
use App\Formule_Express;
use Illuminate\Http\Request;

class Formule_ExpressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Formule_Express = Formule_Express::all();

        return view('Formule_Express.index', compact('Formule_Express'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Formule_Express.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
            'nom'=>'required',
            'nom_anglais'=>'',
            'description'=>'',
            'description_anglais'=>'',
            'fait_maison'=>'',
            'prix'=>'required'
          ]);
          $Formule_Express = new Formule_Express([
            'nom' => $request->get('nom'),
            'nom_anglais' => $request->get('nom_anglais'),
            'description' => $request->get('description'),
            'description_anglais' => $request->get('description_anglais'),
            'fait_maison' => $request->get('fait_maison'),
            'prix' => $request->get('prix')
          ]);
       $Formule_Express->save();
          return redirect('/Formule_Express')->with('success', "L'élément du la Formule Express à bien été ajouté");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Formule_Express = Formule_Express::find($id);

        return view('Formule_Express.edit', compact('Formule_Express'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
            'nom'=>'required',
            'nom_anglais'=>'',
            'description'=>'',
            'description_anglais'=>'',
            'fait_maison' =>'',
            'prix' =>''
          ]);
    
          $Formule_Express = Formule_Express::find($id);
          $Formule_Express->nom = $request->get('nom');
          $Formule_Express->nom_anglais = $request->get('nom_anglais');
          $Formule_Express->description = $request->get('description');
          $Formule_Express->description_anglais = $request->get('description_anglais');
          $Formule_Express->fait_maison = $request->get('fait_maison');
          $Formule_Express->prix = $request->get('prix');
          $Formule_Express->save();
    
          return redirect('/Formule_Express')->with('success', "L'élément du Formule_Express à bien été mis à jour");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Formule_Express = Formule_Express::find($id);
    $Formule_Express->delete();

    return redirect('/Formule_Express')->with("success", "l'élément a bien été suprimé");
    }
}

resources/views/Formule_Express/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container create-Formule_Express">
    <h1 class="text-center">CRÉER UN ÉLÉMENT DE LA FORMULE EXPRESS</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
        <form action="{{ route('Formule_Express.store') }}" method="post">
            <div class="form-group">
                    @csrf
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom" class="form-control" placeholder="Entrez un élément de la formule express">
            </div>

            <div class="form-group">
                <label for="nom_anglais">Nom (traduction anglaise)</label>
                <input type="text" id="nom_anglais" name="nom_anglais" class="form-control" placeholder="Entrez un élément de la formule express en anglais">
            </div>
            
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control" placeholder="Entrez une description">
            </div>


            <div class="form-group">
                <label for="description_anglais">Description (traduction anglaise)</label>
                <input type="text" id="description_anglais" name="description_anglais" class="form-control" placeholder="Entrez une description en anglais">
            </div>

            <div class="form-group">
                <label for="select">Fait maison</label>
                <input type="checkbox" value="1" checked id="fait_maison" name="fait_maison">
            </div>

                 <div class="form-group">
                <label for="prix">Prix</label>
                <input type="text" id="prix" name="prix" class="form-control" placeholder="Entrez un prix">
            </div>

            
            <button type="submit" class="btn btn-success">Valider</button>
        </form>
</div>
@endsection

resources/views/Formule_Express/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container create-Formule_Express">
    <h1 class="text-center">MODIFIER UN ÉLÉMENT DE LA FORMULE EXPRESS</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
        <form action="{{ route('Formule_Express.update', $Formule_Express->id) }}" method="post">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="nom">Nom</label>
            <input type="text" id="nom" name="nom" class="form-control" placeholder="Entrez un élément de Formule_Express" value="{{$Formule_Express->nom}}">
            </div>

            <div class="form-group">
                <label for="nom_anglais">Nom (traduction anglaise)</label>
                <input type="text" id="nom_anglais" name="nom_anglais" class="form-control" placeholder="Entrez un élément de la Formule Express en anglais" value="{{$Formule_Express->nom_anglais}}">
            </div>
            
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control" placeholder="Entrez une description" value="{{$Formule_Express->description}}">
            </div>


            <div class="form-group">
                <label for="description_anglais">Description (traduction anglaise)</label>
                <input type="text" id="description_anglais" name="description_anglais" class="form-control" placeholder="Entrez une description en anglais" value="{{$Formule_Express->description_anglais}}">
            </div>

            <div class="form-group">
                <label for="select">Fait maison</label>
                <input type="checkbox" value="1" checked id="fait_maison" name="fait_maison">
            </div>

             <div class="form-group">
                <label for="prix">Prix</label>
                <input type="text" id="prix" name="prix" class="form-control" placeholder="Entrez un prix" value="{{$Formule_Express->prix}}">
            </div>

            <button type="submit" class="btn btn-success">Valider</button>
        </form>
</div>
@endsection

resources/views/Formule_Express/index.blade.php
@extends('layouts.app')

@section('content')


  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
<div class="card-columns">
        @foreach(App\Formule_Express::all() as $Formule_Express)
        <div class="card">
            <div class="card-header">
                <div class="card-title">Élément de Formule Express</div>
            </div>
            <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><p class="text-center">{{$Formule_Express->nom}}<br>- <br>{{$Formule_Express->nom_anglais}}</p></li>
                    </ul>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i><p class="text-center">{{$Formule_Express->description}} <br> - <br> {{$Formule_Express->description_anglais}} </p></i></li>
                        @if($Formule_Express->fait_maison == 1)
                        <li class="list-group-item crud"><img src="https://monkeychamonix.com/site/wp-content/uploads/2014/08/icon_60175.png" width="50" height="50" alt=""></li>
                        @endif                      </ul>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><p class="text-center">{{$Formule_Express->prix}}</li>
                    </ul>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item crud"><a href="{{ route('Formule_Express.edit',$Formule_Express->id)}}" class="btn btn-primary">Modifier</a>
                            
                                    <form action="{{ route('Formule_Express.destroy', $Formule_Express->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                              Supprimer
                                            </button>
                                          </form>

                                          

                                        </li>
                            </ul>
            </div>
        </div>
        
        @endforeach
        <a class="nav-link" href="{{ route('Formule_Express.create') }}"><button class="btn btn-success">{{ __("Ajouter un élément") }}</button></a>
</div>



@endsection