routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/mentionslegales', function () {
    return view('components/mentionslegales');
});

Route::get('/index_anglais', function () {
    return view('index_anglais');
});
Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('menus', 'MenuController');

Route::resource('menus', 'MenuInfoController');

Route::resource('menu_entree', 'MenuEntreeController');

Route::resource('menu_plat', 'MenuPlatController');

Route::resource('menu_dessert', 'MenuDessertController');

Route::resource('plats', 'PlatController');

Route::resource('Formule_Express', 'Formule_ExpressController');

Route::resource('entrees','EntreesController');

Route::resource('plats', 'PlatController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a style="color:white;" class="navbar-brand" href="{{ url('/admin') }}">
                    <img src="https://image.noelshack.com/fichiers/2019/08/3/1550666908-logoenvt.png" width="70" height="60">

                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a style="color:#00000;" class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a style="color:#00000;" class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                        <li class="nav-item dropdown">
                            <a style="color:#00000;" class="nav-link" href="{{ route('menus.index') }}">{{ __("Voir les éléments du menu") }}</a>
                        </li>

                         <li class="nav-item dropdown">
                            <a style="color:#00000;" class="nav-link" href="{{ route('Formule_Express.index') }}">{{ __("Voir les éléments de la Formule Express") }}</a>
                        </li>

                        <li class="nav-item dropdown">
                                <a style="color:#00000;" class="nav-link" href="{{ route('entrees.index') }}">{{ __("Voir les éléments des entrées") }}</a>
                        </li>
                        <li class="nav-item dropdown">
                                <a style="color:#00000;" class="nav-link" href="{{ route('plats.index') }}">{{ __("Voir les éléments des plats") }}</a>
                        </li>
                            <li class="nav-item dropdown">
                                <a style="color:#00000;" id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Se déconnecter') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                    @yield('content')
            </div>
            
        </main>
    </div>
</body>
</html>